name: CVMFS Service Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Ensure CVMFS Service Image
      - name: Pull or Load CVMFS Service Image
        run: |
          echo "Checking for CVMFS service image..."
          if ! docker pull registry.cern.ch/cvmfs/service:latest; then
            echo "Failed to pull image. Trying to load from tarball..."
            curl -s https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.12.0/cvmfs-service-2.12.0.x86_64.docker.tar.gz | docker load
          fi

      # Step 2: Start CVMFS Service Container
      - name: Start CVMFS Service
        run: |
          echo "Starting CVMFS service container..."
          docker run -d --rm \
            -e CVMFS_CLIENT_PROFILE=single \
            -e CVMFS_REPOSITORIES=sft.cern.ch,sw.hsf.org \
            --cap-add SYS_ADMIN \
            --device /dev/fuse \
            --volume /cvmfs:/cvmfs:shared \
            registry.cern.ch/cvmfs/service:latest

      # Step 3: Verify CVMFS Repositories
      - name: Verify CVMFS Repositories
        run: |
          echo "Probing CVMFS setup..."
          cvmfs_config probe || echo "CVMFS probe failed."
          echo "Testing repository access..."
          ls /cvmfs/sft.cern.ch || echo "sft.cern.ch repository not mounted"
          ls /cvmfs/sw.hsf.org || echo "sw.hsf.org repository not mounted"

      # Step 4: Debug Container State
      - name: Debug Container State
        run: |
          echo "Debugging container environment..."
          docker ps
          docker inspect $(docker ps -q) || echo "No running containers to inspect."

      # Step 5: Stop CVMFS Service (cleanup)
      - name: Stop CVMFS Service
        if: always()
        run: |
          echo "Stopping all CVMFS service containers..."
          docker ps -q --filter ancestor=registry.cern.ch/cvmfs/service:latest | xargs -r docker stop
