name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CONTAINER_IMAGE: ghcr.io/key4hep/key4hep-images/alma9
  DOCKER_RUN: |
    docker run --rm \
      --device /dev/fuse \
      --cap-add SYS_ADMIN \
      --volume /cvmfs:/cvmfs:shared \
      --volume ${{ github.workspace }}:/workspace \
      $CONTAINER_IMAGE

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up CVMFS
      - uses: cvmfs-contrib/github-action-cvmfs@v4

      # Build and test in the container
      - name: Build and test
        shell: bash
        run: |
          ${{ env.DOCKER_RUN }} bash -c "
            set -e
          
            #cd /workspace
            pwd
            ls
            ls /cvmfs/sft.cern.ch
            
            echo '::group::Set-up key4hep'
            source setup.sh

            echo '::group::Configure DDFastCaloSim'
            mkdir -p build
            cmake -B build -S .

            echo '::group::Build DDFastCaloSim'
            cmake --build build -j 4
            source build/thisDDFastCaloSim.sh

            echo '::group::Run simulation'
            chmod +x tests/run_ODD_sim.sh
            source tests/run_ODD_sim.sh
          "

      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: sim_output
          path: tests/run/
          if-no-files-found: error
          retention-days: 7
