name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs:latest
      options: >-
        --privileged
        --device=/dev/fuse
        --cap-add=SYS_ADMIN

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4


      # Run the required setup and commands
      - name: Test
        run: |
          set -e
          echo "::group::Set-up key4hep and dev environment"
          echo $SHELL
          echo $PWD
          ls
          ls /cvmfs/sw.hsf.org
          ls /cvmfs/sw.hsf.org/key4hep/setup.sh
          source setup.sh
          echo "::endgroup::"

          echo "::group::Run format check"
          cmake -D FORMAT_COMMAND=clang-format -P cmake/lint.cmake
          echo "::endgroup::"

          echo "::group::Run spell check"
          cmake -P cmake/spell.cmake
          echo "::endgroup::"

          echo "::group::Configure DDFastCaloSim"
          mkdir -p build
          cmake -B build -S .
          echo "::endgroup::"

          echo "::group::Build DDFastCaloSim"
          cmake --build build -j 4
          source build/thisDDFastCaloSim.sh
          echo "::endgroup::"

          echo "::group::Run simulation"
          chmod +x tests/run_ODD_sim.sh
          ./tests/run_ODD_sim.sh
          echo "::endgroup::"

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: sim_output
          path: tests/run/
          if-no-files-found: error
          retention-days: 7
