name: CVMFS Setup with Service Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-24.04
    container:
      image: registry.cern.ch/cvmfs/service:latest
      options: >-
        --cap-add=SYS_ADMIN
        --device=/dev/fuse
        --volume=/cvmfs:/cvmfs:shared
    steps:
      # Step 1: Verify CVMFS configuration
      - name: Verify CVMFS Configuration
        run: |
          echo "Verifying CVMFS configuration..."
          cvmfs_config chksetup

      # Step 2: Mount repositories
      - name: Mount CVMFS Repositories
        run: |
          echo "Setting up CVMFS repositories..."
          echo "CVMFS_CLIENT_PROFILE=single" >> /etc/cvmfs/default.conf
          echo "CVMFS_REPOSITORIES=sft.cern.ch,sw.hsf.org" >> /etc/cvmfs/default.conf
          cvmfs_config setup
          sleep 5  # Give some time for the service to initialize

      # Step 3: Verify repositories are accessible
      - name: Verify Repositories
        run: |
          echo "Checking mounted repositories..."
          ls /cvmfs/sft.cern.ch || echo "sft.cern.ch repository not mounted"
          ls /cvmfs/sw.hsf.org || echo "sw.hsf.org repository not mounted"

      # Step 4: Use CVMFS Content
      - name: Test CVMFS Content Access
        run: |
          echo "Testing CVMFS content access..."
          ls /cvmfs/sft.cern.ch > /dev/null && echo "sft.cern.ch accessible" || echo "Failed to access sft.cern.ch"
          ls /cvmfs/sw.hsf.org > /dev/null && echo "sw.hsf.org accessible" || echo "Failed to access sw.hsf.org"
