name: Build and Test DDFastCaloSim

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs:latest
      options: |
        --device /dev/fuse
        --cap-add SYS_ADMIN
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # List files to debug presence of setup.sh
      - name: List files
        run: ls -la

      # Run the required setup and commands
      - name: Test
        run: |
          set -e
          echo "::group::Set-up key4hep and dev environment"
          if [ ! -f setup.sh ]; then
            echo "setup.sh not found!" >&2
            exit 1
          fi
          source setup.sh
          echo "::group::Run format check"
          cmake -D FORMAT_COMMAND=clang-format -P cmake/lint.cmake
          echo "::group::Run spell check"
          cmake -P cmake/spell.cmake
          echo "::group::Configure DDFastCaloSim"
          mkdir -p build
          cmake -B build -S .
          echo "::group::Build DDFastCaloSim"
          cmake --build build -j 4
          source build/thisDDFastCaloSim.sh
          echo "::group::Run simulation"
          chmod +x tests/run_ODD_sim.sh
          ./tests/run_ODD_sim.sh

      # Upload artifacts
      - name: Upload simulation output
        uses: actions/upload-artifact@v4
        with:
          name: sim_output
          path: tests/run/
          if-no-files-found: error
          retention-days: 7
