name: Pipeline

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  run:
    env:
      views_path: /cvmfs/sft.cern.ch/lcg/views
      platform: x86_64-el9-gcc13-opt
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # See https://lcginfo.cern.ch/ for info on available LCG releases
        lcg: [LCG_106]
    steps:
      - uses: actions/checkout@v4
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - uses: aidasoft/run-lcg-view@v4
        with:
          release-platform: "${{matrix.lcg}}/${{env.platform}}"
          run: |            
            echo "::group::Set-up key4hep"
            source /cvmfs/sw.hsf.org/key4hep/setup.sh -r 2024-11-28
      