name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Initialize CVMFS on the host
      - name: Initialize CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4

      # Step 2: Checkout the code on the host
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 3: Run container-based steps with bind mount
      - name: List CVMFS Contents Inside Container
        uses: docker://gitlab-registry.cern.ch/linuxsupport/alma9-base
        with:
          args: >
            --volume /cvmfs:/cvmfs:shared
        run: ls /cvmfs/sft.cern.ch/
