name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs:latest
      volumes:
        - /cvmfs:/cvmfs:shared
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      - name: Mock lsb-release
        run: |
          echo "DISTRIB_ID=AlmaLinux" > /etc/lsb-release
          echo "DISTRIB_RELEASE=9" >> /etc/lsb-release
          echo "DISTRIB_CODENAME=Alma" >> /etc/lsb-release
          echo "DISTRIB_DESCRIPTION='AlmaLinux 9'" >> /etc/lsb-release

      - uses: cvmfs-contrib/github-action-cvmfs@v4

      # Run the required setup and commands
      - name: Test
        run: |
          set -e
          echo "::group::Set-up key4hep and dev environment"
          echo $SHELL
          echo $PWD
          ls
          . ./setup.sh

          echo "::group::Run format check"
          cmake -D FORMAT_COMMAND=clang-format -P cmake/lint.cmake

          echo "::group::Run spell check"
          cmake -P cmake/spell.cmake

          echo "::group::Configure DDFastCaloSim"
          mkdir -p build
          cmake -B build -S .

          echo "::group::Build DDFastCaloSim"
          cmake --build build -j 4
          source build/thisDDFastCaloSim.sh

          echo "::group::Run simulation"
          chmod +x tests/run_ODD_sim.sh
          ./tests/run_ODD_sim.sh

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: sim_output
          path: tests/run/
          if-no-files-found: error
          retention-days: 7
