name: Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run:
    env:
      views_path: /cvmfs/sft.cern.ch/lcg/views
      platform: x86_64-el9-gcc13-opt
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # See https://lcginfo.cern.ch/ for info on available LCG releases
        lcg: [LCG_106]
    steps:
      - uses: actions/checkout@v4

      - uses: cvmfs-contrib/github-action-cvmfs@v4

      - uses: aidasoft/run-lcg-view@v4
        with:
          release-platform: "${{matrix.lcg}}/${{env.platform}}"
          run: |            
            echo "::group::Set-up key4hep"
            source setup.sh

            echo "::group::Run simulation"
            chmod +x tests/run_ODD_sim.sh
            ./tests/run_ODD_sim.sh
  test:
    needs: run

    runs-on: ubuntu-24.04
    container:
      # Run in FCS container as we need ROOT
      image: jbeirer/ubuntu24-fastcalosim:latest

      steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Test simulation output
        run: |
          # Install root-diff via go install
          go install go-hep.org/x/hep/groot/cmd/root-diff@latest
          export PATH=$(go env GOPATH)/bin:$PATH

          # Compare the output of the simulation with the reference
          if ! root-diff tests/refs/ODD_sim.root tests/run/ODD_sim.root; then
            echo "Output differs from reference!" >&2
            exit 1
          else
            echo "Output matches reference."
          fi