name: CVMFS Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Pull or load the CVMFS service container image
      - name: Pull or Load CVMFS Service Image
        run: |
          echo "Checking for CVMFS service image..."
          if ! docker pull registry.cern.ch/cvmfs/service:latest; then
            echo "Failed to pull image. Trying to load from tarball..."
            curl -s https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.12.0/cvmfs-service-2.12.0.x86_64.docker.tar.gz | docker load
          fi

      # Step 2: Start the CVMFS service container
      - name: Start CVMFS Service Container
        run: |
          echo "Starting CVMFS service container..."
          docker run -d --rm \
            -e CVMFS_CLIENT_PROFILE=single \
            -e CVMFS_REPOSITORIES=sft.cern.ch,sw.hsf.org \
            --cap-add SYS_ADMIN \
            --device /dev/fuse \
            --volume /cvmfs:/cvmfs:shared \
            --name cvmfs-service \
            registry.cern.ch/cvmfs/service:latest


      # Step 3: Verify CVMFS setup within the container
      - name: Verify CVMFS Setup in Container
        run: |
          echo "Probing CVMFS setup within container..."
          docker exec cvmfs-service cvmfs_config probe || echo "CVMFS probe failed in container."
          echo "Testing repository access within container..."
          docker exec cvmfs-service ls /cvmfs/sft.cern.ch || echo "sft.cern.ch repository not mounted in container."
          docker exec cvmfs-service ls /cvmfs/sw.hsf.org || echo "sw.hsf.org repository not mounted in container."

      # Step 4: Verify CVMFS mount access on host
      - name: Verify CVMFS Access on Host
        run: |
          echo "Checking CVMFS repositories on host..."
          ls /cvmfs/sft.cern.ch || echo "sft.cern.ch repository not mounted on host."
          ls /cvmfs/sw.hsf.org || echo "sw.hsf.org repository not mounted on host."

      # Step 5: Stop the CVMFS service container
      - name: Stop CVMFS Service Container
        run: |
          echo "Stopping CVMFS service container..."
          docker stop cvmfs-service
