name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4

      - name: List CVMFS Contents
        run: ls /cvmfs/sft.cern.ch/

      - name: Run Tests
        run: |
          source /cvmfs/sw.hsf.org/key4hep/setup.sh -r 2024-11-28
          exit 0
