name: CI with CVMFS in Container

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up CVMFS
      - name: Set up CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4

      # Step 3: Run commands in a container
      - name: Run commands in container
        run: |
          docker run --rm \
            --device /dev/fuse \
            --cap-add SYS_ADMIN \
            --volume /cvmfs:/cvmfs:shared \
            gitlab-registry.cern.ch/linuxsupport/alma9-base \
            bash -c "ls /cvmfs/sft.cern.ch/"
