name: Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run:
    env:
      views_path: /cvmfs/sft.cern.ch/lcg/views
      platform: x86_64-el9-gcc13-opt
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # See https://lcginfo.cern.ch/ for info on available LCG releases
        lcg: [LCG_106]
    steps:
      - uses: actions/checkout@v4

      - uses: cvmfs-contrib/github-action-cvmfs@v4

      - uses: aidasoft/run-lcg-view@v4
        with:
          release-platform: "${{matrix.lcg}}/${{env.platform}}"
          run: |            
            echo "::group::Set-up key4hep"
            source setup.sh

            echo "::group::Run simulation"
            chmod +x tests/run_ODD_sim.sh
            ./tests/run_ODD_sim.sh
      - uses: actions/upload-artifact@v4
        with:
          name: sim_output
          path: tests/run/
          if-no-files-found: error
          retention-days: 7