name: CVMFS Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs
      options: >-
        --device /dev/fuse
        --cap-add SYS_ADMIN
        --privileged

    steps:
      - name: Start container
        shell: bash
        run: |
          name=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
            docker run --name container --privileged -v ${GITHUB_WORKSPACE}:/${name} -v ~/.cache/ccache:/root/.cache/ccache -d ghcr.io/key4hep/key4hep-images/alma9-cvmfs tail -f /dev/null
      - name: test
        shell: bash
        run: |
          ls /cvmfs/sw.hsf.org && echo '/cvmfs/sw.hsf.org accessible' || echo '/cvmfs/sw.hsf.org not accessible';
