name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-24.04
    container:
      image: gitlab-registry.cern.ch/linuxsupport/alma9-base
      volumes: /cvmfs:/cvmfs:shared
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4

      - name: List CVMFS Contents
        run: ls /cvmfs/sft.cern.ch/
