name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CONTAINER_IMAGE: ghcr.io/key4hep/key4hep-images/alma9

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up CVMFS
      - uses: cvmfs-contrib/github-action-cvmfs@v4

      # Build and test in the container
      - name: Build and test
        run: |
          docker run --rm \
            --device /dev/fuse \
            --cap-add SYS_ADMIN \
            --volume /cvmfs:/cvmfs:shared \
            --volume ${{ github.workspace }}:/workspace \
            --workdir /workspace \
            ${{ env.CONTAINER_IMAGE }} bash -c "

            echo '::group::Set-up key4hep'
            source setup.sh || exit 1

            echo '::group::Configure DDFastCaloSim'
            mkdir -p build
            cmake -B build -S . || exit 1

            echo '::group::Build DDFastCaloSim'
            cmake --build build -j 4  || exit 1
            source build/thisDDFastCaloSim.sh

            echo '::group::Run simulation'
            chmod +x tests/run_ODD_sim.sh
            source tests/run_ODD_sim.sh || exit 1
          "

      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: sim_output
          path: tests/run/
          if-no-files-found: error
          retention-days: 7
