name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs:latest
      options: >-
        --privileged
        --device=/dev/fuse
        --cap-add=SYS_ADMIN

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Debug CVMFS configuration
      - name: Debug CVMFS Configuration
        run: cat /etc/cvmfs/default.local

      # Check FUSE module
      - name: showconfig
        run: cvmfs_config showconfig

      # Check FUSE module
      - name: bugreport
        run: cvmfs_config bugreport

      - name: probe
        run: |
          set -e
          cvmfs_config probe
          ls /cvmfs/sw.hsf.org || echo "CVMFS content not available"
