name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/key4hep/key4hep-images/alma9-cvmfs:latest
      options: >-
        --privileged
        --device=/dev/fuse
        --cap-add=SYS_ADMIN

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Debug CVMFS configuration
      - name: Debug CVMFS Configuration
        run: cat /etc/cvmfs/default.local

      # Show CVMFS config
      - name: Show Config
        run: cvmfs_config showconfig

      - name: Fix CVMFS Configuration
        run: |
          # Check /etc/cvmfs/default.local
          echo "Old default.local"
          cat /etc/cvmfs/default.local

          # Remove CVMFS_CONFIG_REPOSITORY from default.local if it exists
          sed -i '/^CVMFS_CONFIG_REPOSITORY=/d' /etc/cvmfs/default.local

          # Add CVMFS_CONFIG_REPOSITORY to default.conf
          echo "CVMFS_CONFIG_REPOSITORY=cvmfs-config.cern.ch" >> /etc/cvmfs/default.conf

          echo "CVMFS_REPOSITORIES=sft.cern.ch,sw.hsf.org" >> /etc/cvmfs/default.local

          echo "New default.local"
          cat /etc/cvmfs/default.local

      - name: Setup CVMFS
        run: cvmfs_config setup

      - name: Check setup
        run: cvmfs_config chksetup

      - name: Manual mount
        run: mount -t cvmfs sw.hsf.org /cvmfs/sw.hsf.org

      # Generate Bug Report
      - name: Generate Bug Report
        run: |
          set -e
          cvmfs_config bugreport
          echo "Bug report generated at /tmp/cvmfs-bugreport.*/*.tar.gz"

      # Upload Bug Report
      - name: Upload Bug Report
        uses: actions/upload-artifact@v4
        with:
          name: cvmfs-bugreport
          path: /tmp/cvmfs-bugreport.*/*.tar.gz

      - name: probe
        run: |
          set -e
          cvmfs_config probe
          ls /cvmfs/sw.hsf.org || echo "CVMFS content not available"
          ls /cvmfs/sw.hsf.org/key4hep/setup.sh || echo "key4hep content not available"
